---

- name: "create nm connection {{ conn.conn_name }}"
  become: true
  community.general.nmcli:
    addr_gen_mode6: "{{ conn.addr_gen_mode6 | default(omit) }}"
    ageingtime: "{{ conn.ageingtime | default(omit) }}"
    arp_interval: "{{ conn.arp_interval | default(omit) }}"
    arp_ip_target: "{{ conn.arp_ip_target | default(omit) }}"
    autoconnect: "{{ conn.autoconnect | default(omit) }}"
    conn_name: "{{ conn.conn_name }}"
    dhcp_client_id: "{{ conn.dhcp_client_id | default(omit) }}"
    dns4: "{{ conn.dns4 | default(omit) }}"
    dns4_ignore_auto: "{{ conn.dns4_ignore_auto | default(omit) }}"
    dns4_search: "{{ conn.dns4_search | default(omit) }}"
    dns6: "{{ conn.dns6 | default(omit) }}"
    dns6_ignore_auto: "{{ conn.dns6_ignore_auto | default(omit) }}"
    dns6_search: "{{ conn.dns6_search | default(omit) }}"
    downdelay: "{{ conn.downdelay | default(omit) }}"
    egress: "{{ conn.egress | default(omit) }}"
    flags: "{{ conn.flags | default(omit) }}"
    forwarddelay: "{{ conn.forwarddelay | default(omit) }}"
    gsm: "{{ conn.gsm | default(omit) }}"
    gw4: "{{ conn.gw4 | default(omit) }}"
    gw4_ignore_auto: "{{ conn.gw4_ignore_auto | default(omit) }}"
    gw6: "{{ conn.gw6 | default(omit) }}"
    gw6_ignore_auto: "{{ conn.gw6_ignore_auto | default(omit) }}"
    hairpin: "{{ conn.hairpin | default(omit) }}"
    hellotime: "{{ conn.hellotime | default(omit) }}"
    ifname: "{{ conn.ifname | default(omit) }}"
    ingress: "{{ conn.ingress | default(omit) }}"
    ip4: "{{ conn.ip4 | default(omit) }}"
    ip6: "{{ conn.ip6 | default(omit) }}"
    ip_privacy6: "{{ conn.ip_privacy6 | default(omit) }}"
    ip_tunnel_dev: "{{ conn.ip_tunnel_dev | default(omit) }}"
    ip_tunnel_local: "{{ conn.ip_tunnel_local | default(omit) }}"
    ip_tunnel_remote: "{{ conn.ip_tunnel_remote | default(omit) }}"
    ip_tunnel_input_key: "{{ conn.ip_tunnel_input_key | default(omit) }}"
    ip_tunnel_output_key: "{{ conn.ip_tunnel_output_key | default(omit) }}"
    mac: "{{ conn.mac | default(omit) }}"
    master: "{{ conn.master | default(omit) }}"
    maxage: "{{ conn.maxage | default(omit) }}"
    may_fail4: "{{ conn.may_fail4 | default(omit) }}"
    method4: "{{ conn.method4 | default(omit) }}"
    method6: "{{ conn.method6 | default(omit) }}"
    miimon: "{{ conn.miimon | default(omit) }}"
    mode: "{{ conn.mode | default(omit) }}"
    mtu: "{{ conn.mtu | default(omit) }}"
    never_default4: "{{ conn.never_default4 | default(omit) }}"
    path_cost: "{{ conn.path_cost | default(omit) }}"
    primary: "{{ conn.primary | default(omit) }}"
    priority: "{{ conn.priority | default(omit) }}"
    route_metric4: "{{ conn.route_metric4 | default(omit) }}"
    route_metric6: "{{ conn.route_metric6 | default(omit) }}"
    routes4: "{{ conn.routes4 | default(omit) }}"
    routes4_extended: "{{ conn.routes4_extended | default(omit) }}"
    routes6: "{{ conn.routes6 | default(omit) }}"
    routes6_extended: "{{ conn.routes6_extended | default(omit) }}"
    routing_rules4: "{{ conn.routing_rules4 | default(omit) }}"
    runner: "{{ conn.runner | default(omit) }}"
    runner_hwaddr_policy: "{{ conn.runner_hwaddr_policy | default(omit) }}"
    slavepriority: "{{ conn.slavepriority | default(omit) }}"
    ssid: "{{ conn.ssid | default(omit) }}"
    state: "{{ conn.state | default('present') }}"
    stp: "{{ conn.stp | default(omit) }}"
    type: "{{ conn.type }}"
    updelay: "{{ conn.updelay | default(omit) }}"
    vlandev: "{{ conn.vlandev | default(omit) }}"
    vlanid: "{{ conn.vlanid | default(omit) }}"
    vpn: "{{ conn.vpn | default(omit) }}"
    vxlan_id: "{{ conn.vxlan_id | default(omit) }}"
    vxlan_local: "{{ conn.vxlan_local | default(omit) }}"
    vxlan_remote: "{{ conn.vxlan_remote | default(omit) }}"
    wifi: "{{ conn.wifi | default(omit) }}"
    wifi_sec: "{{ conn.wifi_sec | default(omit) }}"
    wireguard: "{{ conn.wireguard | default(omit) }}"
    xmit_hash_policy: "{{ conn.xmit_hash_policy | default(omit) }}"
    zone: "{{ conn.zone | default(omit) }}"
