---

- name: remove needed packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ network_manager_packages_removals_list | flatten }}"


- name: install needed packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ network_manager_packages_install_list | flatten }}"
