---

- name: Load role metas
  tags:
    - compatibility
  ansible.builtin.include_vars:
    file: "meta/main.yml"

- name: Get role supported platforms
  tags:
    - compatibility
  ansible.builtin.set_fact:
    role_supported_distributions_list: >-
      "{{ galaxy_info.platforms | json_query('[].name')
      | string | default('none') | lower }}"
    role_supported_releases_list: >-
      "{{ (galaxy_info.platforms |
      selectattr('name', 'match', ansible_distribution) |
      list | first).versions | default('none') | lower | string }}"

- name: Get node platform
  tags:
    - compatibility
  ansible.builtin.set_fact:
    ansible_distribution_release: "{{ ansible_distribution_version | string }}"
  when: ansible_distribution_release == ""

- name: Exclude node
  tags:
    - compatibility
  when: >
    ansible_distribution | lower not in role_supported_distributions_list
    or
    (
      ansible_distribution_release | lower not in role_supported_releases_list
      and
      'all' not in role_supported_releases_list | lower
    )
  block:
    - name: Check if this role can be run on this node
      ansible.builtin.fail:
        msg: >-
          "{{ ansible_distribution }}/{{ ansible_distribution_release }}
           is not a supported by this role"
    - name: Exclude this node with unsupported platform
      ansible.builtin.meta: end_host
