---

- name: Generate config
  when:
    - network_manager_configure is defined
    - network_manager_configure == "generate"
  block:
    - name: Load task for packages
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/packages.yml

    - name: Load task for clean old conf systems
      when: network_manager_cleanup_old_systems | bool
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/cleanup_old_systems.yml

    - name: Start and enable service
      become: true
      ansible.builtin.service:
        name: "{{ network_manager_service_name }}"
        state: started
        enabled: true

    - name: Load task for config
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/config.yml

    - name: Load tasks for delete nm connection
      when:
        - network_manager_connections is iterable
        - network_manager_connections | length > 0
        - conn.state == "absent"
      loop: "{{ network_manager_connections | flatten }}"
      loop_control:
        loop_var: conn
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/delete_nm_connections.yml

    - name: Load tasks for create nm connection
      when:
        - network_manager_connections is iterable
        - network_manager_connections | length > 0
        - conn.state == "present"
      loop: "{{ network_manager_connections | flatten }}"
      loop_control:
        loop_var: conn
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/create_nm_connections.yml


- name: Cleanup config
  when:
    - network_manager_configure is defined
    - network_manager_configure == "cleanup"
  block:
    - name: Load task for clean conf nm
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/cleanup_old_nm.yml

    - name: Stop and disable service
      become: true
      ansible.builtin.service:
        name: "{{ network_manager_service_name }}"
        state: stopped
        enabled: false
